[package]
name = "view_bintxt"
version = "0.1.0"
authors = ["Rubens Brandao <git@rubens.io>"]
edition = "2021"

[dependencies]
binaryninja.workspace = true
binaryninjacore-sys.workspace = true
ihex = "3.0.0"
log = "0.4"
srec = "0.2.0"

[lib]
crate-type = ["cdylib"]